using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using RentalCommand.Api.DTOs;
using RentalCommand.Core.Atomic;
using RentalCommand.Core.Authorization;
using RentalCommand.Core.Entities;
using RentalCommand.Core.Enums;

namespace RentalCommand.Api.Services.Domain;

public enum AtomicNoticeDraftOperation { Generate, Update, Dismiss }

public sealed record AtomicNoticeDraftMutationCommand(
    int PortfolioId,
    int ActorUserId,
    Guid AuthSessionId,
    int AccessContextId,
    long ExpectedAccessRevision,
    AtomicNoticeDraftOperation Operation,
    int NoticeDraftId,
    string RequestJson,
    string DeliveryIdempotencyKey) : IAtomicCommandData;

public sealed record AtomicNoticeDraftMutationResult(
    bool Found,
    bool Applied,
    int NoticeDraftId,
    int CreatedCount,
    string ResponseJson) : IAtomicResultData;

/// <summary>
/// Receipt-backed tenant-notice draft generation and review. Generation delegates to the one
/// PostgreSQL INSERT/SELECT command; edit and dismiss return DB-side snapshots from the same
/// transaction as their semantic audit and durable data-update outbox message.
/// </summary>
public sealed class AtomicNoticeDraftMutationHandler
    : IAtomicCommandHandler<AtomicNoticeDraftMutationCommand, AtomicNoticeDraftMutationResult>,
      IAtomicReplayAuthorizer<AtomicNoticeDraftMutationCommand>
{
    public async Task<AtomicNoticeDraftMutationResult> HandleAsync(
        AtomicNoticeDraftMutationCommand command,
        IAtomicWriteAttempt attempt,
        CancellationToken ct)
    {
        Validate(command);
        await attempt.Locking.AcquireAsync(AtomicLockResource.AuthSession, command.AuthSessionId, ct);
        await attempt.Locking.AcquireAsync(
            AtomicLockResource.WorkspaceAccessContext, command.AccessContextId, ct);
        await attempt.Locking.AcquireAsync(AtomicLockResource.Portfolio, command.PortfolioId, ct);
        if (command.NoticeDraftId > 0)
        {
            await attempt.Locking.AcquireAsync(
                AtomicLockResource.NoticeDraft, command.NoticeDraftId, ct);
        }

        var now = await attempt.Persistence.ReadDatabaseClockUtcAsync(ct);
        attempt.UseDatabaseWallClockForAudit(now);
        await RequireCurrentIdentityAsync(command, attempt.Persistence, now, ct);

        return command.Operation switch
        {
            AtomicNoticeDraftOperation.Generate =>
                await GenerateAsync(command, attempt, now, ct),
            AtomicNoticeDraftOperation.Update =>
                await UpdateAsync(command, attempt, now, ct),
            AtomicNoticeDraftOperation.Dismiss =>
                await DismissAsync(command, attempt, now, ct),
            _ => throw new ArgumentOutOfRangeException(nameof(command.Operation)),
        };
    }

    public async Task AuthorizeReplayAsync(
        AtomicNoticeDraftMutationCommand command,
        IAtomicPersistenceSession persistence,
        CancellationToken ct)
    {
        Validate(command);
        var now = await persistence.ReadDatabaseClockUtcAsync(ct);
        await RequireCurrentIdentityAsync(command, persistence, now, ct);
        if (!await HasOperationAuthorityAsync(command, persistence, now, ct))
        {
            throw new UnauthorizedAccessException(
                "The current Team role can no longer manage the requested tenant notice scope.");
        }
    }

    private static async Task<AtomicNoticeDraftMutationResult> GenerateAsync(
        AtomicNoticeDraftMutationCommand command,
        IAtomicWriteAttempt attempt,
        DateTime now,
        CancellationToken ct)
    {
        var request = Read<GenerateNoticeDraftsRequest>(command);
        if (!await HasGenerationAuthorityAsync(command, request, attempt.Persistence, now, ct))
        {
            return EmptyGeneration();
        }

        var generated = await attempt.NoticeDrafts.GenerateManualAsync(
            Scope(command),
            request.RecipientTenantId,
            request.LeaseManagementId,
            request.TenantAccountId,
            request.TenantLedgerEntryId,
            request.NoticeType,
            now,
            ct);
        var createdCount = generated.FirstOrDefault()?.CreatedCount ?? 0;
        if (createdCount > 0)
        {
            attempt.StageSemanticEvent(new AtomicSemanticAudit(
                command.PortfolioId,
                nameof(NoticeDraft),
                0,
                AuditLogOperation.Created,
                UserId: command.ActorUserId,
                ChangeReason: $"{createdCount} tenant notice draft(s) generated by the set command"),
                now);
            StageDataUpdate(attempt, command, 0, "create", now);
        }

        var response = new GenerateNoticeDraftsResponse
        {
            CreatedCount = createdCount,
            Drafts = generated.Select(Map).ToArray(),
        };
        return new AtomicNoticeDraftMutationResult(
            true,
            createdCount > 0,
            generated.FirstOrDefault()?.DraftId ?? 0,
            createdCount,
            JsonSerializer.Serialize(response));
    }

    private static async Task<AtomicNoticeDraftMutationResult> UpdateAsync(
        AtomicNoticeDraftMutationCommand command,
        IAtomicWriteAttempt attempt,
        DateTime now,
        CancellationToken ct)
    {
        var request = Read<UpdateNoticeDraftRequest>(command);
        var draft = await AuthorizedDrafts(command, attempt.Persistence, now)
            .SingleOrDefaultAsync(candidate =>
                candidate.Id == command.NoticeDraftId && candidate.Status == "Draft", ct);
        if (draft is null) return Missing();

        if (!string.IsNullOrWhiteSpace(request.Subject)) draft.Subject = request.Subject.Trim();
        if (!string.IsNullOrWhiteSpace(request.Body)) draft.Body = request.Body.Trim();
        draft.UpdatedAt = now;
        attempt.BindSemanticAudit(draft, Audit(
            command, draft.Id, AuditLogOperation.Updated, "Tenant notice draft copy updated"));
        await attempt.FlushBusinessAsync(ct);
        StageDataUpdate(attempt, command, draft.Id, "update", now);
        return Applied(draft.Id, await SnapshotJsonAsync(command, attempt.Persistence, now, draft.Id, ct));
    }

    private static async Task<AtomicNoticeDraftMutationResult> DismissAsync(
        AtomicNoticeDraftMutationCommand command,
        IAtomicWriteAttempt attempt,
        DateTime now,
        CancellationToken ct)
    {
        var draft = await AuthorizedDrafts(command, attempt.Persistence, now)
            .SingleOrDefaultAsync(candidate =>
                candidate.Id == command.NoticeDraftId && candidate.Status == "Draft", ct);
        if (draft is null) return Missing();

        draft.Status = "Dismissed";
        draft.DismissedAt = now;
        draft.UpdatedAt = now;
        attempt.BindSemanticAudit(draft, Audit(
            command, draft.Id, AuditLogOperation.Updated, "Tenant notice draft dismissed"));
        await attempt.FlushBusinessAsync(ct);
        StageDataUpdate(attempt, command, draft.Id, "update", now);
        return Applied(draft.Id, await SnapshotJsonAsync(command, attempt.Persistence, now, draft.Id, ct));
    }

    private static async Task<bool> HasOperationAuthorityAsync(
        AtomicNoticeDraftMutationCommand command,
        IAtomicPersistenceSession persistence,
        DateTime now,
        CancellationToken ct)
    {
        if (command.Operation is AtomicNoticeDraftOperation.Update or AtomicNoticeDraftOperation.Dismiss)
        {
            return await AuthorizedDrafts(command, persistence, now)
                .AnyAsync(draft => draft.Id == command.NoticeDraftId, ct);
        }

        return await HasGenerationAuthorityAsync(
            command, Read<GenerateNoticeDraftsRequest>(command), persistence, now, ct);
    }

    private static Task<bool> HasGenerationAuthorityAsync(
        AtomicNoticeDraftMutationCommand command,
        GenerateNoticeDraftsRequest request,
        IAtomicPersistenceSession persistence,
        DateTime now,
        CancellationToken ct)
    {
        var authorizedProperties = AuthorizedProperties(command, persistence, now);
        if (!HasRelationshipFilter(request)) return authorizedProperties.AnyAsync(ct);

        return persistence.Query<LeaseManagement>().AsNoTracking().AnyAsync(management =>
            management.PortfolioId == command.PortfolioId
            && authorizedProperties.Any(property =>
                property.Id == management.PropertyId
                && property.PortfolioId == management.PortfolioId)
            && (request.LeaseManagementId == null || management.Id == request.LeaseManagementId.Value)
            && (request.RecipientTenantId == null || management.Parties.Any(party =>
                party.PortfolioId == management.PortfolioId
                && party.TenantId == request.RecipientTenantId.Value))
            && (request.TenantAccountId == null || management.TenantAccount != null
                && management.TenantAccount.PortfolioId == management.PortfolioId
                && management.TenantAccount.Id == request.TenantAccountId.Value)
            && (request.TenantLedgerEntryId == null || management.TenantAccount != null
                && management.TenantAccount.PortfolioId == management.PortfolioId
                && management.TenantAccount.LedgerEntries.Any(entry =>
                    entry.PortfolioId == management.PortfolioId
                    && entry.Id == request.TenantLedgerEntryId.Value)), ct);
    }

    private static IQueryable<NoticeDraft> AuthorizedDrafts(
        AtomicNoticeDraftMutationCommand command,
        IAtomicPersistenceSession persistence,
        DateTime now)
    {
        var authorizedProperties = AuthorizedProperties(command, persistence, now);
        return persistence.Query<NoticeDraft>().Where(draft =>
                draft.PortfolioId == command.PortfolioId
                && draft.PropertyId != null
                && authorizedProperties.Any(property =>
                    property.Id == draft.PropertyId.Value
                    && property.PortfolioId == draft.PortfolioId))
            .AsTracking();
    }

    private static IQueryable<Property> AuthorizedProperties(
        AtomicNoticeDraftMutationCommand command,
        IAtomicPersistenceSession persistence,
        DateTime now)
    {
        var assignments = EffectiveAssignments(command, persistence, now);
        return persistence.Query<Property>().AsNoTracking().Where(property =>
            property.PortfolioId == command.PortfolioId
            && property.DeletedAt == null
            && assignments.Any(assignment =>
                assignment.ScopeKind == MembershipRoleAssignmentScopeKind.AllProperties
                || assignment.ScopeKind == MembershipRoleAssignmentScopeKind.SelectedProperties
                && assignment.SelectedProperties.Any(selected =>
                    selected.PortfolioId == property.PortfolioId
                    && selected.PropertyId == property.Id)));
    }

    private static IQueryable<MembershipRoleAssignment> EffectiveAssignments(
        AtomicNoticeDraftMutationCommand command,
        IAtomicPersistenceSession persistence,
        DateTime now) =>
        persistence.Query<MembershipRoleAssignment>().AsNoTracking().Where(assignment =>
            assignment.PortfolioId == command.PortfolioId
            && assignment.Status == MembershipRoleAssignmentStatus.Active
            && assignment.SuspendedAtUtc == null
            && assignment.RevokedAtUtc == null
            && assignment.EffectiveFromUtc <= now
            && (assignment.EffectiveToUtc == null || assignment.EffectiveToUtc > now)
            && assignment.WorkspaceMembership!.AccessContextId == command.AccessContextId
            && assignment.WorkspaceMembership.PortfolioId == command.PortfolioId
            && assignment.WorkspaceMembership.Status == WorkspaceMembershipStatus.Active
            && assignment.WorkspaceMembership.SuspendedAtUtc == null
            && assignment.WorkspaceMembership.RevokedAtUtc == null
            && assignment.WorkspaceMembership.EffectiveFromUtc <= now
            && (assignment.WorkspaceMembership.EffectiveToUtc == null
                || assignment.WorkspaceMembership.EffectiveToUtc > now)
            && IdentityAuthorized(command, persistence, now).Any()
            && assignment.RoleProfile!.Capabilities.Any(grant =>
                grant.CapabilityDefinition!.Key == CapabilityKeys.TenantNoticesManage
                && grant.CapabilityDefinition.AuthorizationTargetKind
                    == CapabilityAuthorizationTargetKind.Property));

    private static IQueryable<WorkspaceAccessContext> IdentityAuthorized(
        AtomicNoticeDraftMutationCommand command,
        IAtomicPersistenceSession persistence,
        DateTime now) =>
        persistence.Query<WorkspaceAccessContext>().AsNoTracking().Where(context =>
            context.Id == command.AccessContextId
            && context.UserId == command.ActorUserId
            && context.PortfolioId == command.PortfolioId
            && context.AccessRevision == command.ExpectedAccessRevision
            && context.Status == WorkspaceAccessContextStatus.Active
            && context.SuspendedAtUtc == null
            && context.RevokedAtUtc == null
            && persistence.Query<AuthSession>().Any(session =>
                session.Id == command.AuthSessionId
                && session.UserId == command.ActorUserId
                && session.ActiveAccessContextId == command.AccessContextId
                && session.Status == AuthSessionStatus.Active
                && session.RevokedAtUtc == null
                && session.ExpiresAtUtc > now));

    private static async Task RequireCurrentIdentityAsync(
        AtomicNoticeDraftMutationCommand command,
        IAtomicPersistenceSession persistence,
        DateTime now,
        CancellationToken ct)
    {
        if (!await IdentityAuthorized(command, persistence, now).AnyAsync(ct))
        {
            throw new UnauthorizedAccessException("Workspace access changed. Refresh and try again.");
        }
    }

    private static IQueryable<NoticeDraftResponse> SnapshotQuery(
        AtomicNoticeDraftMutationCommand command,
        IAtomicPersistenceSession persistence,
        DateTime now) =>
        AuthorizedDrafts(command, persistence, now).AsNoTracking().Select(draft =>
            new NoticeDraftResponse
            {
                Id = draft.Id,
                LeaseManagementId = draft.LeaseManagementId,
                TenantAccountId = draft.TenantAccountId,
                RecipientLeaseManagementPartyId = draft.RecipientLeaseManagementPartyId,
                LeaseAgreementId = draft.LeaseAgreementId,
                LeaseAddendumId = draft.LeaseAddendumId,
                TenantLedgerEntryId = draft.TenantLedgerEntryId,
                RecipientTenantId = draft.RecipientLeaseManagementParty!.TenantId,
                PropertyId = draft.PropertyId,
                TenantName = (draft.RecipientLeaseManagementParty.Tenant!.FirstName + " "
                    + draft.RecipientLeaseManagementParty.Tenant.LastName).Trim(),
                PropertyName = draft.Property!.Name,
                UnitNumber = draft.LeaseManagement!.Unit!.UnitNumber,
                NoticeType = draft.NoticeType,
                Status = draft.Status,
                Subject = draft.Subject,
                Body = draft.Body,
                Reason = draft.Reason,
                TriggerDate = draft.TriggerDate,
                ConversationId = draft.ConversationId,
                ApprovedChannels = draft.ApprovedChannels,
                CreatedAt = draft.CreatedAt,
                UpdatedAt = draft.UpdatedAt,
                ApprovedAt = draft.ApprovedAt,
                DismissedAt = draft.DismissedAt,
            });

    private static async Task<string> SnapshotJsonAsync(
        AtomicNoticeDraftMutationCommand command,
        IAtomicPersistenceSession persistence,
        DateTime now,
        int id,
        CancellationToken ct) =>
        JsonSerializer.Serialize(await SnapshotQuery(command, persistence, now)
            .SingleAsync(draft => draft.Id == id, ct));

    private static NoticeDraftResponse Map(AtomicGeneratedTenantNoticeDraft draft) => new()
    {
        Id = draft.DraftId,
        LeaseManagementId = draft.LeaseManagementId,
        TenantAccountId = draft.TenantAccountId,
        RecipientLeaseManagementPartyId = draft.RecipientLeaseManagementPartyId,
        LeaseAgreementId = draft.LeaseAgreementId,
        LeaseAddendumId = draft.LeaseAddendumId,
        TenantLedgerEntryId = draft.TenantLedgerEntryId,
        RecipientTenantId = draft.RecipientTenantId,
        PropertyId = draft.PropertyId,
        TenantName = draft.TenantName,
        PropertyName = draft.PropertyName,
        UnitNumber = draft.UnitNumber,
        NoticeType = draft.NoticeType,
        Status = draft.Status,
        Subject = draft.Subject,
        Body = draft.Body,
        Reason = draft.Reason,
        TriggerDate = draft.TriggerDate,
        ConversationId = draft.ConversationId,
        ApprovedChannels = draft.ApprovedChannels,
        CreatedAt = draft.CreatedAt,
        UpdatedAt = draft.UpdatedAt,
        ApprovedAt = draft.ApprovedAt,
        DismissedAt = draft.DismissedAt,
    };

    private static bool HasRelationshipFilter(GenerateNoticeDraftsRequest request) =>
        request.RecipientTenantId is not null
        || request.LeaseManagementId is not null
        || request.TenantAccountId is not null
        || request.TenantLedgerEntryId is not null;

    private static WorkspaceReadScope Scope(AtomicNoticeDraftMutationCommand command) =>
        new(command.PortfolioId, command.ActorUserId, command.AuthSessionId,
            command.AccessContextId, command.ExpectedAccessRevision);

    private static AtomicSemanticAudit Audit(
        AtomicNoticeDraftMutationCommand command,
        int id,
        AuditLogOperation operation,
        string reason) =>
        new(command.PortfolioId, nameof(NoticeDraft), id, operation,
            UserId: command.ActorUserId, ChangeReason: reason);

    private static void StageDataUpdate(
        IAtomicWriteAttempt attempt,
        AtomicNoticeDraftMutationCommand command,
        int entityId,
        string operation,
        DateTime now) =>
        attempt.StageOutbox(new OutboxMessage
        {
            PortfolioId = command.PortfolioId,
            MessageType = "data-update",
            Payload = JsonSerializer.Serialize(new
            {
                entityType = nameof(NoticeDraft),
                entityId,
                operation,
                data = new { },
            }),
            IdempotencyKey = $"{command.DeliveryIdempotencyKey}:notice-draft-data-update",
            CreatedAtUtc = now,
            NextAttemptAtUtc = now,
        });

    private static T Read<T>(AtomicNoticeDraftMutationCommand command) where T : class =>
        JsonSerializer.Deserialize<T>(command.RequestJson)
        ?? throw new ArgumentException("Tenant notice mutation request payload is invalid.");

    private static void Validate(AtomicNoticeDraftMutationCommand command)
    {
        if (command.PortfolioId <= 0
            || command.ActorUserId <= 0
            || command.AuthSessionId == Guid.Empty
            || command.AccessContextId <= 0
            || command.ExpectedAccessRevision <= 0
            || string.IsNullOrWhiteSpace(command.RequestJson)
            || string.IsNullOrWhiteSpace(command.DeliveryIdempotencyKey)
            || command.DeliveryIdempotencyKey.Length > 128
            || ((command.Operation is AtomicNoticeDraftOperation.Update
                    or AtomicNoticeDraftOperation.Dismiss)
                && command.NoticeDraftId <= 0))
        {
            throw new ArgumentException(
                "Portfolio, actor, access revision, request, target, and delivery identifiers are required.");
        }
    }

    private static AtomicNoticeDraftMutationResult EmptyGeneration() =>
        new(true, false, 0, 0, JsonSerializer.Serialize(new GenerateNoticeDraftsResponse()));

    private static AtomicNoticeDraftMutationResult Missing() => new(false, false, 0, 0, "{}");

    private static AtomicNoticeDraftMutationResult Applied(int id, string responseJson) =>
        new(true, true, id, 0, responseJson);
}

public static class AtomicNoticeDraftMutation
{
    public static readonly AtomicJsonResultCodec<AtomicNoticeDraftMutationResult> Codec =
        new("rental.notice-draft-mutation.v1");

    public static AtomicNoticeDraftMutationCommand Command<TRequest>(
        WorkspaceReadScope scope,
        AtomicNoticeDraftOperation operation,
        int noticeDraftId,
        string operationKey,
        TRequest request) =>
        new(scope.PortfolioId, scope.UserId, scope.SessionId, scope.AccessContextId,
            scope.AccessRevision, operation, noticeDraftId, JsonSerializer.Serialize(request), operationKey);

    public static AtomicCommandIdentity Identity(AtomicNoticeDraftMutationCommand command) =>
        new($"rental.notice-draft.{command.Operation.ToString().ToLowerInvariant()}",
            $"{command.PortfolioId}:{command.AccessContextId}:{command.Operation}:" +
            $"{command.NoticeDraftId}:{command.DeliveryIdempotencyKey}");
}
