using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using RentalCommand.Api.DTOs;
using RentalCommand.Core.Atomic;
using RentalCommand.Core.Notifications;
using RentalCommand.Data.Notifications;
using RentalCommand.Core.Authorization;
using RentalCommand.Core.Entities;
using RentalCommand.Core.Enums;
using RentalCommand.Api.Services;
using RentalCommand.Data;
using RentalCommand.Data.Authorization;

namespace RentalCommand.Api.Services.Domain;

public enum AtomicNoticeDraftOperation { Generate, Update, Dismiss }

public sealed record AtomicNoticeDraftMutationCommand(
    int PortfolioId,
    int ActorUserId,
    [property: AtomicFingerprintIgnore]
    Guid AuthSessionId,
    [property: AtomicFingerprintIgnore]
    int AccessContextId,
    [property: AtomicFingerprintIgnore]
    long ExpectedAccessRevision,
    AtomicNoticeDraftOperation Operation,
    int NoticeDraftId,
    string RequestJson,
    [property: AtomicFingerprintIgnore]
    string DeliveryIdempotencyKey) : IAtomicCommandData;

public sealed record AtomicNoticeDraftMutationResult(
    bool Found,
    bool Applied,
    int NoticeDraftId,
    int CreatedCount,
    string ResponseJson);

/// <summary>
/// Receipt-backed tenant-notice draft generation and review. Generation delegates to the one
/// PostgreSQL INSERT/SELECT command; edit and dismiss return DB-side snapshots from the same
/// transaction as their semantic audit and durable data-update outbox message.
/// </summary>
public sealed class AtomicNoticeDraftMutationRule
{
    private readonly RentalCommandDbContext _db;

    public AtomicNoticeDraftMutationRule(RentalCommandDbContext db) => _db = db;

    public async Task<AtomicNoticeDraftMutationResult> ExecuteAsync(
        AtomicNoticeDraftMutationCommand command,
        IAtomicCommandContext attempt,
        CancellationToken ct)
    {
        Validate(command);
        await attempt.AcquireLockAsync("AuthSession", command.AuthSessionId, ct);
        await attempt.AcquireLockAsync(
            "WorkspaceAccessContext", command.AccessContextId, ct);
        await attempt.AcquireLockAsync("Portfolio", command.PortfolioId, ct);
        if (command.NoticeDraftId > 0)
        {
            await attempt.AcquireLockAsync(
                "NoticeDraft", command.NoticeDraftId, ct);
        }

        var now = await AtomicCommandDbClock.ReadDatabaseClockUtcAsync(_db, ct);
        attempt.UseDatabaseWallClockForAudit(now);
        await RequireCurrentIdentityAsync(command, _db, now, ct);

        return command.Operation switch
        {
            AtomicNoticeDraftOperation.Generate =>
                await GenerateAsync(command, attempt, now, ct),
            AtomicNoticeDraftOperation.Update =>
                await UpdateAsync(command, attempt, now, ct),
            AtomicNoticeDraftOperation.Dismiss =>
                await DismissAsync(command, attempt, now, ct),
            _ => throw new ArgumentOutOfRangeException(nameof(command.Operation)),
        };
    }

    public async Task AuthorizeAsync(
        AtomicNoticeDraftMutationCommand command,
        IAtomicCommandContext context,
        CancellationToken ct)
    {
        Validate(command);
        var now = await context.ReadDatabaseClockUtcAsync(ct);
        await RequireCurrentIdentityAsync(command, _db, now, ct);
        if (!await HasOperationAuthorityAsync(command, _db, now, ct))
        {
            throw new UnauthorizedAccessException(
                "The current Team role can no longer manage the requested tenant notice scope.");
        }
    }

    private async Task<AtomicNoticeDraftMutationResult> GenerateAsync(
        AtomicNoticeDraftMutationCommand command,
        IAtomicCommandContext attempt,
        DateTime now,
        CancellationToken ct)
    {
        var request = Read<GenerateNoticeDraftsRequest>(command);
        if (!await HasGenerationAuthorityAsync(command, request, _db, now, ct))
        {
            return EmptyGeneration();
        }

        var generated = await AtomicNoticeDraftPersistence.GenerateManualAsync(_db,
            attempt,
            Scope(command),
            request.RecipientTenantId,
            request.LeaseManagementId,
            request.TenantAccountId,
            request.TenantLedgerEntryId,
            request.NoticeType,
            now,
            ct);
        var createdCount = generated.FirstOrDefault()?.CreatedCount ?? 0;
        if (createdCount > 0)
        {
            attempt.StageSemanticEvent(new AtomicSemanticAudit(
                command.PortfolioId,
                nameof(NoticeDraft),
                0,
                AuditLogOperation.Created,
                UserId: command.ActorUserId,
                ChangeReason: $"{createdCount} tenant notice draft(s) generated by the set command"),
                now);
            StageCreatedDraftUpdates(attempt, command, generated, now);
        }

        var response = new GenerateNoticeDraftsResponse
        {
            CreatedCount = createdCount,
            Drafts = generated.Select(Map).ToArray(),
        };
        return new AtomicNoticeDraftMutationResult(
            true,
            createdCount > 0,
            generated.FirstOrDefault()?.DraftId ?? 0,
            createdCount,
            JsonSerializer.Serialize(response));
    }

    private async Task<AtomicNoticeDraftMutationResult> UpdateAsync(
        AtomicNoticeDraftMutationCommand command,
        IAtomicCommandContext attempt,
        DateTime now,
        CancellationToken ct)
    {
        var request = Read<UpdateNoticeDraftRequest>(command);
        var draft = await AuthorizedDrafts(command, _db, now)
            .SingleOrDefaultAsync(candidate =>
                candidate.Id == command.NoticeDraftId && candidate.Status == "Draft", ct);
        if (draft is null) return Missing();

        if (!string.IsNullOrWhiteSpace(request.Subject)) draft.Subject = request.Subject.Trim();
        if (!string.IsNullOrWhiteSpace(request.Body)) draft.Body = request.Body.Trim();
        draft.UpdatedAt = now;
        attempt.BindSemanticAudit(draft, Audit(
            command, draft.Id, AuditLogOperation.Updated, "Tenant notice draft copy updated"));
        await attempt.FlushBusinessAsync(ct);
        StageDataUpdate(attempt, command, draft.Id, "update", now);
        return Applied(draft.Id, await SnapshotJsonAsync(command, _db, now, draft.Id, ct));
    }

    private async Task<AtomicNoticeDraftMutationResult> DismissAsync(
        AtomicNoticeDraftMutationCommand command,
        IAtomicCommandContext attempt,
        DateTime now,
        CancellationToken ct)
    {
        var draft = await AuthorizedDrafts(command, _db, now)
            .SingleOrDefaultAsync(candidate =>
                candidate.Id == command.NoticeDraftId && candidate.Status == "Draft", ct);
        if (draft is null) return Missing();

        draft.Status = "Dismissed";
        draft.DismissedAt = now;
        draft.UpdatedAt = now;
        attempt.BindSemanticAudit(draft, Audit(
            command, draft.Id, AuditLogOperation.Updated, "Tenant notice draft dismissed"));
        await attempt.FlushBusinessAsync(ct);
        StageDataUpdate(attempt, command, draft.Id, "update", now);
        return Applied(draft.Id, await SnapshotJsonAsync(command, _db, now, draft.Id, ct));
    }

    private async Task<bool> HasOperationAuthorityAsync(
        AtomicNoticeDraftMutationCommand command,
        RentalCommandDbContext db,
        DateTime now,
        CancellationToken ct)
    {
        if (command.Operation is AtomicNoticeDraftOperation.Update or AtomicNoticeDraftOperation.Dismiss)
        {
            return await AuthorizedDrafts(command, db, now)
                .AnyAsync(draft => draft.Id == command.NoticeDraftId, ct);
        }

        return await HasGenerationAuthorityAsync(
            command, Read<GenerateNoticeDraftsRequest>(command), db, now, ct);
    }

    private Task<bool> HasGenerationAuthorityAsync(
        AtomicNoticeDraftMutationCommand command,
        GenerateNoticeDraftsRequest request,
        RentalCommandDbContext db,
        DateTime now,
        CancellationToken ct)
    {
        var authorizedProperties = AuthorizedProperties(command, db, now);
        if (!HasRelationshipFilter(request)) return authorizedProperties.AnyAsync(ct);

        return db.Set<LeaseManagement>().AsNoTracking().AnyAsync(management =>
            management.PortfolioId == command.PortfolioId
            && authorizedProperties.Any(property =>
                property.Id == management.PropertyId
                && property.PortfolioId == management.PortfolioId)
            && (request.LeaseManagementId == null || management.Id == request.LeaseManagementId.Value)
            && (request.RecipientTenantId == null || management.Parties.Any(party =>
                party.PortfolioId == management.PortfolioId
                && party.TenantId == request.RecipientTenantId.Value))
            && (request.TenantAccountId == null || management.TenantAccount != null
                && management.TenantAccount.PortfolioId == management.PortfolioId
                && management.TenantAccount.Id == request.TenantAccountId.Value)
            && (request.TenantLedgerEntryId == null || management.TenantAccount != null
                && management.TenantAccount.PortfolioId == management.PortfolioId
                && management.TenantAccount.LedgerEntries.Any(entry =>
                    entry.PortfolioId == management.PortfolioId
                    && entry.Id == request.TenantLedgerEntryId.Value)), ct);
    }

    private IQueryable<NoticeDraft> AuthorizedDrafts(
        AtomicNoticeDraftMutationCommand command,
        RentalCommandDbContext db,
        DateTime now)
    {
        var authorizedProperties = AuthorizedProperties(command, db, now);
        return db.Set<NoticeDraft>().Where(draft =>
                draft.PortfolioId == command.PortfolioId
                && draft.PropertyId != null
                && authorizedProperties.Any(property =>
                    property.Id == draft.PropertyId.Value
                    && property.PortfolioId == draft.PortfolioId))
            .AsTracking();
    }

    private IQueryable<Property> AuthorizedProperties(
        AtomicNoticeDraftMutationCommand command,
        RentalCommandDbContext db,
        DateTime now)
    {
        return db.Set<Property>().AsNoTracking().WhereAuthorizedForScope(
            db,
            Scope(command),
            CapabilityKeys.TenantNoticesManage,
            now);
    }

    private IQueryable<WorkspaceAccessContext> IdentityAuthorized(
        AtomicNoticeDraftMutationCommand command,
        RentalCommandDbContext db,
        DateTime now) =>
        db.Set<WorkspaceAccessContext>().AsNoTracking().Where(context =>
            context.Id == command.AccessContextId
            && context.UserId == command.ActorUserId
            && context.PortfolioId == command.PortfolioId
            && context.AccessRevision == command.ExpectedAccessRevision
            && context.Status == WorkspaceAccessContextStatus.Active
            && context.SuspendedAtUtc == null
            && context.RevokedAtUtc == null
            && db.Set<AuthSession>().Any(session =>
                session.Id == command.AuthSessionId
                && session.UserId == command.ActorUserId
                && session.ActiveAccessContextId == command.AccessContextId
                && session.Status == AuthSessionStatus.Active
                && session.RevokedAtUtc == null
                && session.ExpiresAtUtc > now));

    private async Task RequireCurrentIdentityAsync(
        AtomicNoticeDraftMutationCommand command,
        RentalCommandDbContext db,
        DateTime now,
        CancellationToken ct)
    {
        if (!await IdentityAuthorized(command, db, now).AnyAsync(ct))
        {
            throw new UnauthorizedAccessException("Workspace access changed. Refresh and try again.");
        }
    }

    private IQueryable<NoticeDraftResponse> SnapshotQuery(
        AtomicNoticeDraftMutationCommand command,
        RentalCommandDbContext db,
        DateTime now) =>
        AuthorizedDrafts(command, db, now).AsNoTracking().Select(draft =>
            new NoticeDraftResponse
            {
                Id = draft.Id,
                LeaseManagementId = draft.LeaseManagementId,
                TenantAccountId = draft.TenantAccountId,
                RecipientLeaseManagementPartyId = draft.RecipientLeaseManagementPartyId,
                LeaseAgreementId = draft.LeaseAgreementId,
                LeaseAddendumId = draft.LeaseAddendumId,
                TenantLedgerEntryId = draft.TenantLedgerEntryId,
                RecipientTenantId = draft.RecipientLeaseManagementParty!.TenantId,
                PropertyId = draft.PropertyId,
                TenantName = (draft.RecipientLeaseManagementParty.Tenant!.FirstName + " "
                    + draft.RecipientLeaseManagementParty.Tenant.LastName).Trim(),
                PropertyName = draft.Property!.Name,
                UnitNumber = draft.LeaseManagement!.Unit!.UnitNumber,
                NoticeType = draft.NoticeType,
                Status = draft.Status,
                Subject = draft.Subject,
                Body = draft.Body,
                Reason = draft.Reason,
                TriggerDate = draft.TriggerDate,
                ConversationId = draft.ConversationId,
                ApprovedChannels = draft.ApprovedChannels,
                CreatedAt = draft.CreatedAt,
                UpdatedAt = draft.UpdatedAt,
                ApprovedAt = draft.ApprovedAt,
                DismissedAt = draft.DismissedAt,
            });

    private async Task<string> SnapshotJsonAsync(
        AtomicNoticeDraftMutationCommand command,
        RentalCommandDbContext db,
        DateTime now,
        int id,
        CancellationToken ct) =>
        JsonSerializer.Serialize(await SnapshotQuery(command, db, now)
            .SingleAsync(draft => draft.Id == id, ct));

    private NoticeDraftResponse Map(AtomicGeneratedTenantNoticeDraft draft) => new()
    {
        Id = draft.DraftId,
        LeaseManagementId = draft.LeaseManagementId,
        TenantAccountId = draft.TenantAccountId,
        RecipientLeaseManagementPartyId = draft.RecipientLeaseManagementPartyId,
        LeaseAgreementId = draft.LeaseAgreementId,
        LeaseAddendumId = draft.LeaseAddendumId,
        TenantLedgerEntryId = draft.TenantLedgerEntryId,
        RecipientTenantId = draft.RecipientTenantId,
        PropertyId = draft.PropertyId,
        TenantName = draft.TenantName,
        PropertyName = draft.PropertyName,
        UnitNumber = draft.UnitNumber,
        NoticeType = draft.NoticeType,
        Status = draft.Status,
        Subject = draft.Subject,
        Body = draft.Body,
        Reason = draft.Reason,
        TriggerDate = draft.TriggerDate,
        ConversationId = draft.ConversationId,
        ApprovedChannels = draft.ApprovedChannels,
        CreatedAt = draft.CreatedAt,
        UpdatedAt = draft.UpdatedAt,
        ApprovedAt = draft.ApprovedAt,
        DismissedAt = draft.DismissedAt,
    };

    private bool HasRelationshipFilter(GenerateNoticeDraftsRequest request) =>
        request.RecipientTenantId is not null
        || request.LeaseManagementId is not null
        || request.TenantAccountId is not null
        || request.TenantLedgerEntryId is not null;

    private WorkspaceReadScope Scope(AtomicNoticeDraftMutationCommand command) =>
        new(command.PortfolioId, command.ActorUserId, command.AuthSessionId,
            command.AccessContextId, command.ExpectedAccessRevision);

    private AtomicSemanticAudit Audit(
        AtomicNoticeDraftMutationCommand command,
        int id,
        AuditLogOperation operation,
        string reason) =>
        new(command.PortfolioId, nameof(NoticeDraft), id, operation,
            UserId: command.ActorUserId, ChangeReason: reason);

    internal static void StageCreatedDraftUpdates(
        IAtomicCommandContext attempt,
        AtomicNoticeDraftMutationCommand command,
        IReadOnlyList<AtomicGeneratedTenantNoticeDraft> generated,
        DateTime now)
    {
        foreach (var draft in generated.Where(candidate => candidate.WasCreated))
        {
            if (draft.DraftId <= 0)
                throw new InvalidOperationException("Generated notice draft has no persisted entity id.");
            StageDataUpdate(attempt, command, draft.DraftId, "create", now);
        }
    }

    private static void StageDataUpdate(
        IAtomicCommandContext attempt,
        AtomicNoticeDraftMutationCommand command,
        int entityId,
        string operation,
        DateTime now) =>
        attempt.StageOutbox(new OutboxMessage
        {
            PortfolioId = command.PortfolioId,
            MessageType = "data-update",
            Payload = JsonSerializer.Serialize(new
            {
                entityType = nameof(NoticeDraft),
                entityId,
                operation,
                data = new { },
            }),
            IdempotencyKey =
                $"{command.DeliveryIdempotencyKey}:notice-draft:{entityId}:data-update",
            CreatedAtUtc = now,
            NextAttemptAtUtc = now,
        });

    private T Read<T>(AtomicNoticeDraftMutationCommand command) where T : class =>
        JsonSerializer.Deserialize<T>(command.RequestJson)
        ?? throw new ArgumentException("The tenant notice update is invalid.");

    private void Validate(AtomicNoticeDraftMutationCommand command)
    {
        if (command.PortfolioId <= 0
            || command.ActorUserId <= 0
            || command.AuthSessionId == Guid.Empty
            || command.AccessContextId <= 0
            || command.ExpectedAccessRevision <= 0
            || string.IsNullOrWhiteSpace(command.RequestJson)
            || string.IsNullOrWhiteSpace(command.DeliveryIdempotencyKey)
            || command.DeliveryIdempotencyKey.Length > 128
            || ((command.Operation is AtomicNoticeDraftOperation.Update
                    or AtomicNoticeDraftOperation.Dismiss)
                && command.NoticeDraftId <= 0))
        {
            throw new ArgumentException(
                "Portfolio, actor, access revision, request, target, and delivery identifiers are required.");
        }
    }

    private AtomicNoticeDraftMutationResult EmptyGeneration() =>
        new(true, false, 0, 0, JsonSerializer.Serialize(new GenerateNoticeDraftsResponse()));

    private AtomicNoticeDraftMutationResult Missing() => new(false, false, 0, 0, "{}");

    private AtomicNoticeDraftMutationResult Applied(int id, string responseJson) =>
        new(true, true, id, 0, responseJson);
}

public static class AtomicNoticeDraftMutation
{
    public static readonly AtomicJsonResultCodec<AtomicNoticeDraftMutationResult> Codec =
        new("rental.notice-draft-mutation.v1");

    public static AtomicNoticeDraftMutationCommand Command<TRequest>(
        WorkspaceReadScope scope,
        AtomicNoticeDraftOperation operation,
        int noticeDraftId,
        string operationKey,
        TRequest request) =>
        new(scope.PortfolioId, scope.UserId, scope.SessionId, scope.AccessContextId,
            scope.AccessRevision, operation, noticeDraftId, JsonSerializer.Serialize(request), operationKey);

    public static AtomicCommandIdentity Identity(AtomicNoticeDraftMutationCommand command) =>
        new($"rental.notice-draft.{command.Operation.ToString().ToLowerInvariant()}",
            $"{command.PortfolioId}:{command.AccessContextId}:{command.Operation}:" +
            $"{command.NoticeDraftId}:{command.DeliveryIdempotencyKey}");

    public static TransactionalWrite<AtomicNoticeDraftMutationCommand, AtomicNoticeDraftMutationResult> Write(
        RentalCommandDbContext db,
        AtomicNoticeDraftMutationCommand command)
    {
        var handler = new AtomicNoticeDraftMutationRule(db);
        return new(
            Identity(command).CommandType,

            command,
            Codec.ContractName,
            WriteLockPlan.None,
            handler.ExecuteAsync,
            handler.AuthorizeAsync);
    }
}
