using System.Globalization;
using System.Text.Json;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using RentalCommand.Core.Enums;
using RentalCommand.Core.Leasing;

namespace RentalCommand.Api.Services.Domain;

public sealed record LeaseAddendumRenderData
{
    public required string AddendumNumber { get; init; }
    public required DateOnly EffectiveFromOn { get; init; }
    public DateOnly? EffectiveThroughOn { get; init; }
    public required string LandlordName { get; init; }
    public required string TenantName { get; init; }
    public required string PropertyAddress { get; init; }
    public required string TermsPayload { get; init; }
    public IReadOnlyList<LegalDocumentIssuanceFinancialEffect> FinancialEffects { get; init; } = [];
}

public interface ILeaseAddendumPdfGenerator
{
    byte[] Generate(LeaseAddendumRenderData data);
}

/// <summary>Server-owned fallback renderer for an immutable Addendum draft.</summary>
public sealed class LeaseAddendumPdfGenerator : ILeaseAddendumPdfGenerator
{
    public byte[] Generate(LeaseAddendumRenderData data)
    {
        using var terms = JsonDocument.Parse(data.TermsPayload);
        var formattedTerms = JsonSerializer.Serialize(terms.RootElement, new JsonSerializerOptions
        {
            WriteIndented = true,
        });
        return Document.Create(container => container.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(40);
            page.DefaultTextStyle(style => style.FontSize(10).LineHeight(1.3f));
            page.Header().Text("Lease Addendum").FontSize(20).Bold().FontColor(Colors.Blue.Darken2);
            page.Content().PaddingTop(16).Column(column =>
            {
                column.Spacing(10);
                column.Item().Text($"Addendum number: {data.AddendumNumber}").SemiBold();
                column.Item().Text($"Landlord: {data.LandlordName}");
                column.Item().Text($"Tenant: {data.TenantName}");
                column.Item().Text($"Premises: {data.PropertyAddress}");
                column.Item().Text(data.EffectiveThroughOn is { } through
                    ? $"Effective: {data.EffectiveFromOn:MMMM d, yyyy} through {through:MMMM d, yyyy}"
                    : $"Effective: {data.EffectiveFromOn:MMMM d, yyyy}");
                column.Item().PaddingTop(8).Text("Financial effects").FontSize(12).Bold();
                if (data.FinancialEffects.Count == 0)
                {
                    column.Item().Text("This Addendum has no separate financial effects.");
                }
                else
                {
                    foreach (var effect in data.FinancialEffects)
                    {
                        column.Item().BorderLeft(2).BorderColor(Colors.Blue.Lighten2).PaddingLeft(8)
                            .Text(DescribeEffect(effect));
                    }
                }
                column.Item().PaddingTop(8).Text("Canonical addendum terms").FontSize(12).Bold();
                column.Item().Border(1).BorderColor(Colors.Grey.Lighten1).Padding(10)
                    .Text(formattedTerms).FontSize(8);
                column.Item().PaddingTop(16).Text(
                    "By signing, the parties adopt this Addendum as part of the referenced lease agreement.");
            });
            page.Footer().AlignCenter().Text("Generated by Rental Command").FontSize(8)
                .FontColor(Colors.Grey.Darken1);
        })).GeneratePdf();
    }

    private static string DescribeEffect(LegalDocumentIssuanceFinancialEffect effect)
    {
        var amount = effect.Amount.ToString("C", CultureInfo.GetCultureInfo("en-US"));
        var label = effect.EffectType switch
        {
            LeaseAddendumFinancialEffectType.RecurringRentDelta =>
                $"Recurring rent adjustment: {amount} {effect.Currency}",
            LeaseAddendumFinancialEffectType.OneTimeCharge =>
                $"One-time charge: {amount} {effect.Currency}",
            LeaseAddendumFinancialEffectType.DepositObligationDelta =>
                $"Security-deposit obligation adjustment: {amount} {effect.Currency}",
            _ => $"Financial effect: {amount} {effect.Currency}",
        };
        var timing = effect.DueOn is { } due
            ? $"due {due:MMMM d, yyyy}"
            : effect.EffectiveFromOn is { } from && effect.EffectiveThroughOn is { } through
                ? $"effective {from:MMMM d, yyyy} through {through:MMMM d, yyyy}"
                : effect.EffectiveFromOn is { } effective
                    ? $"effective {effective:MMMM d, yyyy}"
                    : "effective as stated in this Addendum";
        var chargeCode = string.IsNullOrWhiteSpace(effect.ChargeCode)
            ? string.Empty
            : $"; charge code {effect.ChargeCode}";
        var description = string.IsNullOrWhiteSpace(effect.Description)
            ? string.Empty
            : $". {effect.Description.Trim()}";
        return $"{label}; {timing}{chargeCode}{description}";
    }
}
