import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../accounting/accounting_repository.dart';
import '../analytics/analytics_repository.dart';
import '../appointments/appointments_repository.dart';
import '../applications/applications_repository.dart';
import '../banking/banking_repository.dart';
import '../deposits/deposits_repository.dart';
import '../inspections/inspections_repository.dart';
import '../leases/leases_repository.dart';
import '../maintenance/work_orders_repository.dart';
import '../messages/messages_repository.dart';
import '../money/money_repository.dart';
import '../notices/notices_repository.dart';
import '../notifications/notifications_repository.dart';
import '../owner_reports/owner_reports_repository.dart';
import '../payments/payments_repository.dart';
import '../properties/properties_repository.dart';
import '../recurring_maintenance/recurring_maintenance_repository.dart';
import '../scan/scan_repository.dart';
import '../settings/notification_settings_repository.dart';
import '../team/team_repository.dart';
import '../tenants/tenants_repository.dart';
import '../vendors/vendors_repository.dart';
import 'getting_started_provider.dart';
import 'onboarding_repository.dart';

void refreshPortfolioDataAfterGoLive(WidgetRef ref) {
  ref.invalidate(sandboxStateProvider);
  ref.invalidate(gettingStartedSignalsProvider);

  ref.invalidate(moneySnapshotProvider);
  ref.invalidate(pastDueProvider);
  ref.invalidate(expensesListProvider);
  ref.invalidate(applicationsProvider);
  ref.invalidate(bankingSummaryProvider);
  ref.invalidate(bankingTransactionsProvider);
  ref.invalidate(bankingReviewQueueProvider);
  ref.invalidate(inspectionsProvider);
  ref.invalidate(inspectionTemplatesProvider);
  ref.invalidate(inspectionPropertiesProvider);
  ref.invalidate(scanListFamilyProvider);
  ref.invalidate(vendorsProvider);
  ref.invalidate(availableForLeaseTenantsProvider);
  ref.invalidate(noticeDraftsProvider);
  ref.invalidate(recurringPropertiesProvider);
  ref.invalidate(recurringUnitsProvider);
  ref.invalidate(recurringVendorsProvider);
  ref.invalidate(leasePaymentsProvider);
  ref.invalidate(paymentReceiptProvider);
  ref.invalidate(leaseLedgerProvider);
  ref.invalidate(propertyDetailProvider);
  ref.invalidate(propertyLeasesProvider);
  ref.invalidate(unitsProvider);
  ref.invalidate(tenantDetailProvider);
  ref.invalidate(tenantLeasesProvider);
  ref.invalidate(workOrderDetailProvider);
  ref.invalidate(appointmentDetailProvider);
  ref.invalidate(conversationProvider);

  ref.read(analyticsOverviewProvider.notifier).refresh();
  ref.read(appointmentsProvider.notifier).refresh();
  ref.read(depositsProvider.notifier).refresh();
  ref.read(propertiesProvider.notifier).refresh();
  ref.read(tenantsProvider.notifier).refresh();
  ref.read(leasesProvider.notifier).refresh();
  ref.read(workOrdersProvider.notifier).refresh();
  ref.read(conversationsProvider.notifier).refresh();
  ref.read(unreadCountProvider.notifier).refresh();
  ref.read(inboxProvider.notifier).refresh();
  ref.read(accountingSummaryProvider.notifier).refresh();
  ref.read(paymentsProvider.notifier).refresh();
  ref.read(leasesForPaymentProvider.notifier).load();
  ref.read(recurringMaintenanceProvider.notifier).refresh();
  ref.read(ownerSummariesProvider.notifier).refresh();
  ref.read(notificationSettingsProvider.notifier).refresh();
  ref.read(teamProvider.notifier).refresh();
  ref.read(propertiesForWoProvider.notifier).load();
}
