using RentalCommand.Core.Enums;
using RentalCommand.Core.Interfaces;

namespace RentalCommand.Core.Entities;

/// <summary>
/// One billing period in a <see cref="Loan"/>'s amortization schedule, generated by the
/// <c>DebtServiceWorker</c>. The principal/interest/escrow split is computed once and is immutable:
/// the next period reads its opening balance from this row's <see cref="BalanceAfter"/>, and
/// Schedule E sums <see cref="InterestAmount"/> across the year (principal is excluded — never
/// deductible). Cash flow sums <see cref="TotalAmount"/> (the full P+I+escrow that left the account).
/// </summary>
public class LoanPayment : IPortfolioScoped
{
    public int Id { get; set; }
    public int PortfolioId { get; set; }
    public int LoanId { get; set; }

    /// <summary>Billing period "yyyy-MM"; the idempotency key (one payment per loan per period).</summary>
    public string PeriodKey { get; set; } = string.Empty;

    public DateTime DueDate { get; set; }
    public DateTime? PaidDate { get; set; }

    /// <summary>Interest portion for the period (deductible on Schedule E).</summary>
    public decimal InterestAmount { get; set; }

    /// <summary>Principal portion for the period (reduces the balance; NOT deductible).</summary>
    public decimal PrincipalAmount { get; set; }

    /// <summary>Escrow portion for the period (the cash paid toward escrowed taxes/insurance).</summary>
    public decimal EscrowAmount { get; set; }

    /// <summary>Full payment that left the account: principal + interest + escrow.</summary>
    public decimal TotalAmount { get; set; }

    /// <summary>Outstanding principal after this payment; the next period's opening balance.</summary>
    public decimal BalanceAfter { get; set; }

    public LoanPaymentStatus Status { get; set; } = LoanPaymentStatus.Scheduled;

    /// <summary>
    /// True when the scheduled P&amp;I did not cover the period's interest (negative-amortization guard,
    /// spec §18): principal was forced to 0 and the balance left unchanged. Surfaced so the owner can
    /// see a mis-entered payment rather than silently growing the balance.
    /// </summary>
    public bool PaymentDoesNotCoverInterest { get; set; }

    public DateTime CreatedAt { get; set; }

    public Portfolio? Portfolio { get; set; }
    public Loan? Loan { get; set; }
}
