<script lang="ts">
	import { ArrowLeft, Building, ShieldCheck } from '@lucide/svelte';
</script>

<svelte:head>
	<title>Privacy Policy - Rental Command</title>
	<meta
		name="description"
		content="Rental Command privacy policy: what information is collected, how it is used, and how to contact us about privacy questions."
	/>
</svelte:head>

<div class="privacy-shell min-h-dvh overflow-y-auto bg-background text-foreground">
	<header class="border-b border-border/60 bg-background/90 backdrop-blur">
		<div class="mx-auto flex max-w-4xl items-center justify-between px-5 py-4 sm:px-8">
			<a href="/welcome" class="flex items-center gap-2 text-sm font-semibold tracking-tight">
				<span
					class="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary ring-1 ring-inset ring-primary/20"
				>
					<Building class="h-4 w-4" />
				</span>
				Rental Command
			</a>
			<a
				href="/welcome"
				class="inline-flex items-center gap-1.5 text-sm font-medium text-muted-foreground transition-colors hover:text-foreground"
			>
				<ArrowLeft class="h-4 w-4" />
				Home
			</a>
		</div>
	</header>

	<main class="mx-auto max-w-4xl px-5 py-10 sm:px-8 sm:py-14">
		<div class="mb-8">
			<span
				class="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-xs font-medium text-primary"
			>
				<ShieldCheck class="h-3.5 w-3.5" />
				Privacy
			</span>
			<h1 class="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">
				Rental Command Privacy Policy
			</h1>
			<p class="mt-2 text-sm text-muted-foreground">Last updated: 18 June 2026</p>
		</div>

		<article class="policy-content">
			<p>
				Rental Command ("Rental Command", "we", "us") is a property-management application
				that landlords and property managers use to run their rental business - managing
				properties, tenants, leases, rent payments, maintenance, inspections, documents, and
				rental applications. This Privacy Policy explains what personal information the app
				collects, why we collect it, how it is stored and shared, and the choices you have.
			</p>

			<p>
				The app is provided by the operator of Rental Command. If you have any questions or
				requests about your data, contact us at <strong>jcoble@rentalcommand.net</strong>.
			</p>

			<h2>1. Who This Policy Covers</h2>
			<p>
				Rental Command is a business tool used by a <strong>landlord/property manager</strong>
				(the "account holder"). Through the app, the account holder records information about
				their <strong>tenants, rental applicants, prospective tenants, property owners, and vendors</strong>.
				This policy describes our handling of all of that information.
			</p>
			<p>
				We do <strong>not</strong> target or knowingly collect data from children. The app is
				intended for adults running or participating in a residential-rental relationship.
			</p>

			<h2>2. Information We Collect</h2>
			<p>
				We collect the following categories of information. Not every field applies to every
				user - we only collect what is entered into, or generated by, the app.
			</p>

			<h3>a. Account and login information</h3>
			<ul>
				<li>
					Your name and display name, email address, phone number, and a securely hashed password
					used to sign in.
				</li>
				<li>Account timestamps such as account creation and last sign-in.</li>
				<li>
					For property owners and management entities: contact details, mailing address, and a
					tax identification number where provided, used for tax statements such as 1099s.
				</li>
			</ul>

			<h3>b. Tenant, applicant, and prospect information</h3>
			<ul>
				<li>
					Names, email addresses, phone numbers, home/mailing addresses, date of birth, and
					emergency-contact details for tenants and rental applicants.
				</li>
				<li>
					Rental-application details: current and prior address, employer, and stated monthly
					income.
				</li>
				<li>
					For applicants who use the optional photo-autofill feature, identity and income
					details <strong>extracted from a photo of an ID or pay stub</strong> that the applicant
					uploads.
				</li>
				<li>Prospective-tenant showing names and emails for scheduled appointments.</li>
			</ul>

			<h3>c. Financial and payment information</h3>
			<ul>
				<li>
					Rent and charge records, amounts due and paid, payment dates and methods, security
					deposit amounts and deductions, and expense/receipt records.
				</li>
				<li>For scanned checks: payer name, check number, and bank name.</li>
				<li>
					<strong
						>We do not store full payment-card numbers, card security codes (CVV), or full
						bank-account/routing numbers.</strong
					>
					Card payments are processed by <strong>Stripe</strong>, and we store only Stripe
					references, such as a customer or payment-method identifier. Bank connections are made
					through a banking-data provider (<strong>Plaid</strong>), and we store only
					<strong>encrypted</strong> access tokens plus a <strong>masked</strong> account number
					and the institution/account name.
				</li>
				<li>At most, the last four digits of a card may be stored when scanned from a receipt.</li>
			</ul>

			<h3>d. Background-screening information (with consent)</h3>
			<ul>
				<li>
					When a rental applicant gives <strong>explicit consent</strong>, we may run a
					background/credit screening through a third-party screening provider. We record the
					consent itself, including the date and the IP address it was given from, for compliance
					with the Fair Credit Reporting Act.
				</li>
				<li>
					The screening provider's hosted experience collects the sensitive identity information
					needed to perform the screening. Rental Command stores only workflow and compliance metadata,
					such as provider/reference, status and dates, consumer-reporting-agency contact information,
					and the landlord's decision and reason.
				</li>
				<li>
					Rental Command does <strong>not</strong> store Social Security numbers, raw consumer reports,
					criminal or eviction details, credit scores or bands, or a provider recommendation.
				</li>
				<li>Where required, we generate and store an adverse-action notice.</li>
			</ul>

			<h3>e. Documents, scans, photos, and signatures</h3>
			<ul>
				<li>
					Documents and images you upload or scan, for example lease PDFs, receipts, ID/pay-stub
					photos used for applications, and inspection photos.
				</li>
				<li>
					Electronic-signature records for leases and other documents, including the signer's
					name and email, the typed and/or <strong>drawn (handwritten) signature image</strong>,
					consent, signing timestamp, and a signing audit trail (IP address and device/browser
					information) as required for legally valid e-signatures.
				</li>
				<li>
					These files are stored on <strong>our own application server's file storage</strong>,
					not in a public or third-party cloud storage bucket.
				</li>
			</ul>

			<h3>f. Communications</h3>
			<ul>
				<li>
					The content of messages between landlord and tenant, outbound text messages to vendors,
					and the notifications the app generates.
				</li>
				<li>
					Notification delivery preferences. Any messaging-provider credentials are stored
					<strong>encrypted</strong>.
				</li>
			</ul>

			<h3>g. Device and technical information</h3>
			<ul>
				<li>
					A <strong>push-notification token</strong> and your device platform (Android/iOS/web),
					so we can send you notifications.
				</li>
				<li>
					Security and audit data tied to authentication, signing, and record changes, including
					IP addresses, device/browser user-agent information, sign-in timestamps, and an audit
					log of changes to records.
				</li>
			</ul>

			<h3>h. Device permissions (Android)</h3>
			<p>The Android app may request the following permissions, only for the stated purpose:</p>
			<ul>
				<li>
					<strong>Camera / Photos</strong> - to take or attach photos of receipts, IDs,
					inspections, and documents.
				</li>
				<li>
					<strong>Microphone (record audio)</strong> - to capture voice memos/commands you
					initiate.
				</li>
				<li>
					<strong>Notifications</strong> - to deliver push notifications you have enabled.
				</li>
			</ul>
			<p>You can grant or deny these at any time in your device settings.</p>

			<h2>3. Why We Collect It</h2>
			<p>
				We use the information solely to <strong>operate the Rental Command service for the
					account holder</strong>, including to:
			</p>
			<ul>
				<li>
					Provide and maintain the app's property-, tenant-, lease-, and payment-management
					features.
				</li>
				<li>
					Process rent and deposit payments and connect bank accounts through our payment and
					banking providers.
				</li>
				<li>Run rental-application intake and, with consent, applicant screening.</li>
				<li>Generate and store documents, leases, e-signatures, and notices.</li>
				<li>Send notifications and messages you have configured.</li>
				<li>
					Keep the service secure, prevent fraud and abuse, maintain an audit trail, and comply
					with our legal obligations.
				</li>
			</ul>
			<p>
				We do <strong>not</strong> use this information for advertising, and the app does
				<strong>not</strong> contain ads.
			</p>

			<h2>4. How We Share Information</h2>
			<p>We do <strong>not sell</strong> your personal information.</p>
			<p>We share information only as needed to operate the service, with:</p>
			<ul>
				<li>
					<strong>Service providers</strong> acting on our behalf, including Stripe for payment
					processing, Plaid or a comparable banking-data provider for bank-account connectivity,
					Google Firebase Cloud Messaging / Apple Push Notification service for push
					notifications, a background-screening provider when an applicant consents to screening,
					and an SMS/messaging provider to send text notifications you enable.
				</li>
				<li>
					<strong>The account holder</strong> and authorized users of that landlord's account,
					who can see the tenant/applicant/property records they manage.
				</li>
				<li>
					<strong>Legal and safety</strong> recipients, where we are required to disclose
					information by law, or to protect rights, safety, and the integrity of the service.
				</li>
			</ul>
			<p>
				If the service is ever transferred as part of a business transaction, information may be
				transferred subject to this policy.
			</p>

			<h2>5. How We Protect Information</h2>
			<ul>
				<li>Connections between the app and our servers are encrypted in transit (HTTPS/TLS).</li>
				<li>
					Sensitive secrets, such as bank-provider access tokens and messaging-provider
					credentials, are stored encrypted at rest.
				</li>
				<li>Passwords are stored only as secure cryptographic hashes, never in plain text.</li>
				<li>Access to records is restricted to the account that owns them.</li>
			</ul>
			<p>
				No method of transmission or storage is 100% secure, but we take reasonable measures to
				protect your information.
			</p>

			<h2>6. Data Retention</h2>
			<p>
				We retain personal information for as long as the account holder maintains an active
				account and the records are needed to provide the service, and as required to meet legal,
				tax, accounting, and audit obligations. Many records support a soft-delete and are removed
				or anonymized when no longer needed. When information is no longer required, we delete or
				de-identify it.
			</p>

			<h2>7. Your Choices and Rights</h2>
			<p>
				Depending on where you live, you may have rights to access, correct, export, or delete
				your personal information, and to withdraw consent where processing is based on consent,
				such as background screening.
			</p>
			<ul>
				<li>Account holders can edit and delete much of the data directly in the app.</li>
				<li>
					Tenants, applicants, and other individuals whose data a landlord entered can contact
					us, or the landlord who manages their records, to make a request.
				</li>
				<li>
					To request access to or deletion of your data, or to ask a question about this policy,
					contact us at <strong>jcoble@rentalcommand.net</strong>. We will respond consistent
					with applicable law. Note that we may need to retain certain records to meet legal
					obligations.
				</li>
			</ul>

			<h2>8. Children's Privacy</h2>
			<p>
				Rental Command is not directed to children under 13 (or the equivalent age in your
				jurisdiction), and we do not knowingly collect their personal information. If you believe
				a child's information has been provided to us, contact us so we can remove it.
			</p>

			<h2>9. Changes to This Policy</h2>
			<p>
				We may update this Privacy Policy from time to time. We will revise the "Last updated"
				date above and, where appropriate, provide additional notice. Continued use of the app
				after an update means you accept the revised policy.
			</p>

			<h2>10. Contact Us</h2>
			<p>
				For any privacy question or request, contact:<br />
				<strong>Rental Command</strong><br />
				Email: <strong>jcoble@rentalcommand.net</strong>
			</p>
		</article>
	</main>
</div>

<style>
	.policy-content {
		color: var(--foreground);
		font-size: 0.97rem;
		line-height: 1.7;
	}

	.policy-content :global(p) {
		margin: 0 0 1rem;
		color: color-mix(in srgb, var(--foreground) 88%, var(--muted-foreground));
	}

	.policy-content :global(h2) {
		margin: 2.4rem 0 0.7rem;
		padding-bottom: 0.4rem;
		border-bottom: 1px solid var(--border);
		font-size: 1.25rem;
		font-weight: 650;
		letter-spacing: 0;
	}

	.policy-content :global(h3) {
		margin: 1.4rem 0 0.45rem;
		font-size: 1rem;
		font-weight: 650;
		letter-spacing: 0;
	}

	.policy-content :global(ul) {
		margin: 0 0 1.2rem;
		padding-left: 1.35rem;
		color: color-mix(in srgb, var(--foreground) 88%, var(--muted-foreground));
	}

	.policy-content :global(li) {
		margin: 0.35rem 0;
	}

	.policy-content :global(strong) {
		color: var(--foreground);
		font-weight: 650;
	}
</style>
