<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RentalCommand.Core</RootNamespace>
    <UserSecretsId>4f48ec32-1aee-4c1b-a14a-6370b541a666</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <!-- Provides IdentityUser<TKey> for ApplicationUser : IdentityUser<int> -->
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RentalCommand.Core.Tests" />
  </ItemGroup>

</Project>
