using Microsoft.EntityFrameworkCore;
using RentalCommand.Core.Atomic;
using RentalCommand.Core.Automation;
using RentalCommand.Core.Entities;
using RentalCommand.Core.Enums;

namespace RentalCommand.Data.Payments;

/// <summary>
/// Materializes a bounded set of due recurring tenant-charge occurrences inside the caller's
/// atomic transaction. It does not open a transaction or save outside the command context.
/// </summary>
public sealed class ApplyRecurringTenantChargeBatchHandler
    : IAtomicCommandHandler<
        ApplyRecurringTenantChargeBatchCommand,
        ApplyRecurringTenantChargeBatchResult>
{
    private const int MaximumBatchSize = 1_000;
    private const int MaximumOccurrencesPerSchedule = 120;
    private const int SystemActorId = 0;
    private const string ActorLabel = "system:recurring-tenant-charge";

    private readonly RentalCommandDbContext _db;

    public ApplyRecurringTenantChargeBatchHandler(RentalCommandDbContext db) => _db = db;

    public async Task<ApplyRecurringTenantChargeBatchResult> HandleAsync(
        ApplyRecurringTenantChargeBatchCommand command,
        IAtomicCommandContext context,
        CancellationToken ct)
    {
        Validate(command);

        var businessDate = DateOnly.FromDateTime(command.BusinessNowUtc);
        var schedules = await _db.RecurringTenantCharges
            .Include(schedule => schedule.TenantAccount)
            .Include(schedule => schedule.LeaseAgreement)
            .Include(schedule => schedule.LedgerAccount)
            .Where(schedule => schedule.IsActive
                && schedule.NextRunDate <= businessDate)
            .OrderBy(schedule => schedule.Id)
            .Take(command.BatchSize)
            .ToListAsync(ct);

        var occurrences = BuildOccurrences(schedules, businessDate);
        if (occurrences.Count == 0)
            return new ApplyRecurringTenantChargeBatchResult(0);

        var occurrenceKeys = occurrences
            .Select(occurrence => occurrence.BusinessKey)
            .ToArray();
        var existingKeys = await _db.TenantLedgerEntries
            .AsNoTracking()
            .Where(entry => occurrenceKeys.Contains(entry.BusinessKey))
            .Select(entry => entry.BusinessKey)
            .ToListAsync(ct);
        var existingKeySet = existingKeys.ToHashSet(StringComparer.Ordinal);
        var newOccurrences = occurrences
            .Where(occurrence => !existingKeySet.Contains(occurrence.BusinessKey))
            .ToArray();

        foreach (var occurrence in newOccurrences)
        {
            ValidateSchedule(occurrence.Schedule);
            var charge = new TenantLedgerEntry
            {
                PortfolioId = occurrence.Schedule.PortfolioId,
                TenantAccountId = occurrence.Schedule.TenantAccountId,
                EntryType = TenantLedgerEntryType.ManualCharge,
                Direction = TenantLedgerDirection.Debit,
                Amount = occurrence.Schedule.Amount,
                Currency = occurrence.Schedule.Currency,
                EffectiveOn = occurrence.RunDate,
                DueOn = occurrence.RunDate,
                PostedAtUtc = command.BusinessNowUtc,
                Description = $"{occurrence.Schedule.DisplayName} ({occurrence.RunDate:yyyy-MM})",
                BusinessKey = occurrence.BusinessKey,
                LeaseAgreementId = occurrence.Schedule.LeaseAgreementId,
                CreatedByUserId = occurrence.Schedule.TenantAccount!.CreatedByUserId,
            };
            _db.TenantLedgerEntries.Add(charge);
            occurrence.Charge = charge;
        }

        if (newOccurrences.Length > 0)
        {
            // Journal source ids are generated by PostgreSQL. Flush the business rows while the
            // caller's transaction remains open, then attach their journals to that same context.
            await context.FlushBusinessAsync(ct);
            foreach (var occurrence in newOccurrences)
            {
                await TenantAccountingPosting.PostTenantChargeAsync(
                    _db,
                    context,
                    occurrence.Charge!,
                    SystemActorId,
                    occurrence.Schedule.LedgerAccount!.SystemKey,
                    ct,
                    ActorLabel);
            }
        }

        foreach (var schedule in schedules)
        {
            var nextRunDate = schedule.NextRunDate;
            while (nextRunDate <= businessDate)
            {
                if (schedule.EffectiveEndOn is DateOnly endOn && nextRunDate >= endOn)
                {
                    schedule.IsActive = false;
                    break;
                }

                nextRunDate = NextOccurrence(nextRunDate, schedule.MonthlyDueDay);
            }

            schedule.NextRunDate = nextRunDate;
            schedule.UpdatedAtUtc = command.BusinessNowUtc;
        }

        return new ApplyRecurringTenantChargeBatchResult(newOccurrences.Length);
    }

    public async Task AuthorizeReplayAsync(
        ApplyRecurringTenantChargeBatchCommand command,
        IAtomicCommandContext context,
        CancellationToken ct)
    {
        Validate(command);
        await _db.RecurringTenantCharges
            .AsNoTracking()
            .Where(schedule => schedule.IsActive)
            .Select(schedule => schedule.Id)
            .Take(1)
            .ToListAsync(ct);
    }

    private static IReadOnlyList<Occurrence> BuildOccurrences(
        IReadOnlyList<RecurringTenantCharge> schedules,
        DateOnly businessDate)
    {
        var occurrences = new List<Occurrence>();
        foreach (var schedule in schedules)
        {
            ValidateSchedule(schedule);
            var runDate = schedule.NextRunDate;
            var count = 0;
            while (runDate <= businessDate && count < MaximumOccurrencesPerSchedule)
            {
                if (schedule.EffectiveEndOn is null || runDate < schedule.EffectiveEndOn.Value)
                {
                    occurrences.Add(new Occurrence(
                        schedule,
                        runDate,
                        $"recurring-tenant-charge:{schedule.Id}:{runDate:yyyy-MM}"));
                }

                runDate = NextOccurrence(runDate, schedule.MonthlyDueDay);
                count++;
            }
        }

        return occurrences;
    }

    private static void Validate(ApplyRecurringTenantChargeBatchCommand command)
    {
        if (command.RunToken == Guid.Empty)
            throw new ArgumentException("The recurring tenant-charge run token is required.");
        if (command.BusinessNowUtc.Kind != DateTimeKind.Utc)
            throw new ArgumentException("The recurring tenant-charge business time must be UTC.");
        if (command.BatchSize is <= 0 or > MaximumBatchSize)
            throw new ArgumentOutOfRangeException(
                nameof(command.BatchSize),
                $"The recurring tenant-charge batch size must be between 1 and {MaximumBatchSize}.");
    }

    private static void ValidateSchedule(RecurringTenantCharge schedule)
    {
        if (schedule.PortfolioId <= 0
            || schedule.TenantAccountId <= 0
            || schedule.LeaseAgreementId <= 0
            || schedule.LedgerAccountId <= 0)
        {
            throw new InvalidOperationException(
                "A recurring tenant-charge schedule is missing a required portfolio, tenant, lease, or account mapping.");
        }

        if (schedule.Amount <= 0)
            throw new InvalidOperationException("A recurring tenant-charge schedule must have a positive amount.");
        if (string.IsNullOrWhiteSpace(schedule.Currency))
            throw new InvalidOperationException("A recurring tenant-charge schedule must have a currency.");
        if (schedule.LedgerAccount is null || string.IsNullOrWhiteSpace(schedule.LedgerAccount.SystemKey))
        {
            throw new InvalidOperationException(
                "A recurring tenant-charge schedule requires an active configured income account mapping.");
        }

        if (!schedule.LedgerAccount.IsActive
            || schedule.LedgerAccount.PortfolioId != schedule.PortfolioId)
        {
            throw new InvalidOperationException(
                "A recurring tenant-charge schedule requires an active income account in the same portfolio.");
        }

        if (schedule.TenantAccount is null
            || schedule.TenantAccount.PortfolioId != schedule.PortfolioId
            || !string.Equals(schedule.TenantAccount.Currency, schedule.Currency, StringComparison.Ordinal))
        {
            throw new InvalidOperationException(
                "A recurring tenant-charge schedule must match its tenant account portfolio and currency.");
        }

        if (schedule.LeaseAgreement is null
            || schedule.LeaseAgreement.PortfolioId != schedule.PortfolioId)
        {
            throw new InvalidOperationException(
                "A recurring tenant-charge schedule must reference a lease agreement in the same portfolio.");
        }
    }

    private static DateOnly NextOccurrence(DateOnly runDate, short monthlyDueDay)
    {
        var nextMonth = runDate.AddMonths(1);
        var day = Math.Min(monthlyDueDay, DateTime.DaysInMonth(nextMonth.Year, nextMonth.Month));
        return new DateOnly(nextMonth.Year, nextMonth.Month, day);
    }

    private sealed record Occurrence(
        RecurringTenantCharge Schedule,
        DateOnly RunDate,
        string BusinessKey)
    {
        public TenantLedgerEntry? Charge { get; set; }
    }
}
