// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RentalCommand.Data.Migrations;

[DbContext(typeof(RentalCommandDbContext))]
[Migration("20260716140000_AddWorkspaceLlmCredentials")]
partial class AddWorkspaceLlmCredentials
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);
        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("RentalCommand.Core.Entities.WorkspaceLlmCredential", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("ApiKeyCipherText").IsRequired().HasMaxLength(4000)
                .HasColumnType("character varying(4000)");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("LastTestedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("ModelId").IsRequired().HasMaxLength(128)
                .HasColumnType("character varying(128)");
            b.Property<int>("PortfolioId").HasColumnType("integer");
            b.Property<string>("Provider").IsRequired().HasMaxLength(32)
                .HasColumnType("character varying(32)");
            b.Property<DateTime?>("RotatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("PortfolioId").IsUnique();
            b.ToTable("WorkspaceLlmCredentials");
        });

        modelBuilder.Entity("RentalCommand.Core.Entities.LlmUsageEvidence", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
            b.Property<decimal>("EstimatedCostUsd").HasPrecision(18, 8)
                .HasColumnType("numeric(18,8)");
            b.Property<string>("Feature").IsRequired().HasMaxLength(80)
                .HasColumnType("character varying(80)");
            b.Property<int>("InputUnits").HasColumnType("integer");
            b.Property<int>("LatencyMilliseconds").HasColumnType("integer");
            b.Property<string>("ModelId").IsRequired().HasMaxLength(128)
                .HasColumnType("character varying(128)");
            b.Property<DateTime>("OccurredAtUtc").HasColumnType("timestamp with time zone");
            b.Property<int>("OutputUnits").HasColumnType("integer");
            b.Property<int>("PortfolioId").HasColumnType("integer");
            b.Property<string>("Provider").IsRequired().HasMaxLength(32)
                .HasColumnType("character varying(32)");
            b.HasKey("Id");
            b.HasIndex("PortfolioId", "OccurredAtUtc");
            b.ToTable("LlmUsageEvidence");
        });
    }
}
