// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RentalCommand.Data;

#nullable disable

namespace RentalCommand.Data.Migrations
{
    [DbContext(typeof(RentalCommandDbContext))]
    [Migration("20260728231500_EnforceUniqueBankReconciliationTargets")]
    partial class EnforceUniqueBankReconciliationTargets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            new TargetModelSnapshot().Build(modelBuilder);
#pragma warning restore 612, 618
        }

        private sealed class TargetModelSnapshot : RentalCommandDbContextModelSnapshot
        {
            public void Build(ModelBuilder modelBuilder) => BuildModel(modelBuilder);
        }
    }
}
