import { sveltekit } from '@sveltejs/kit/vite';
import tailwindcss from '@tailwindcss/vite';
import { defineConfig, loadEnv } from 'vite';
import fs from 'fs';

export default defineConfig(({ mode }) => {
	const env = loadEnv(mode, '.', '');
	const apiTarget = env.API_URL || 'https://localhost:5666';

	// HTTPS via locally-trusted mkcert certs (generated by scripts/start-dev.sh).
	// Falls back to HTTP if the certs are absent. Mirrors EdiPlatform's setup.
	const httpsConfig =
		fs.existsSync('.cert/key.pem') && fs.existsSync('.cert/cert.pem')
			? { key: fs.readFileSync('.cert/key.pem'), cert: fs.readFileSync('.cert/cert.pem') }
			: undefined;

	return {
		plugins: [tailwindcss(), sveltekit()],
		server: {
			port: 5667,
			strictPort: true,
			host: true,
			https: httpsConfig,
			proxy: {
				'/api': {
					target: apiTarget,
					changeOrigin: true,
					secure: false,
					// The SvelteKit route at src/routes/api/auth/refresh/+server.ts must handle
					// POST /api/auth/refresh itself (it reads the httpOnly refresh-token cookie and
					// forwards server-side to the API's /api/v1/auth/refresh). Without this bypass the
					// '/api' proxy would forward it to the API, which has no /api/auth/refresh route
					// (only /api/v1/...), 404ing. Returning the request path tells Vite to skip the
					// proxy and let SvelteKit serve it. All other /api/* requests proxy as before.
					bypass: (req) => {
						if (req.url && req.url.split('?')[0] === '/api/auth/refresh') {
							return req.url;
						}
					}
				}
			}
		}
	};
});
