import { sveltekit } from '@sveltejs/kit/vite';
import tailwindcss from '@tailwindcss/vite';
import { defineConfig, loadEnv } from 'vite';
import fs from 'fs';

export default defineConfig(({ mode }) => {
	const env = loadEnv(mode, '.', '');
	const apiTarget = env.API_URL || 'https://localhost:5666';

	// HTTPS via locally-trusted mkcert certs (generated by scripts/start-dev.sh).
	// Falls back to HTTP if the certs are absent. Mirrors EdiPlatform's setup.
	const httpsConfig =
		fs.existsSync('.cert/key.pem') && fs.existsSync('.cert/cert.pem')
			? { key: fs.readFileSync('.cert/key.pem'), cert: fs.readFileSync('.cert/cert.pem') }
			: undefined;

	return {
		plugins: [tailwindcss(), sveltekit()],
		server: {
			port: 5667,
			strictPort: true,
			host: true,
			https: httpsConfig,
			proxy: {
				'/api': {
					target: apiTarget,
					changeOrigin: true,
					secure: false
				}
			}
		}
	};
});
